portfolio:
  funds:
    - code: SPT02
      name: YK Portföy İkinci Fon Sepeti Fonu
      target_weight: 0.3
      units: 1004.402161
    - code: AFO
      name: Ak Portföy Altın Fonu
      target_weight: 0.2
      units: 7457.427411
    - code: YMH
      name: YK Portföy Hisse Senedi Stratejisi Fonu
      target_weight: 0.2
      units: 6181.978913
    - code: ADP
      name: Ak Portföy BIST Banka Endeksi Hisse Senedi Fonu
      target_weight: 0.15
      units: 5682.674888
    - code: TLY
      name: Tera Portföy Birinci Serbest Fon
      target_weight: 0.15
      units: 0.752619
  cash_balance_try: 0
  cash_target_weight: 0
  instruments:
    - type: fund
      code: YFBL7
      name: YAPIKREDİ LİKİT FON
      target_weight: 0.25
      units: 315632
    - type: fund
      code: GTZ
      name: GPY GÜMÜŞ FON
      target_weight: 0.4
      units: 51561
    - type: fund
      code: GTA
      name: GPY ALTIN FONU
      target_weight: 0.25
      units: 360177
    - type: fx
      code: USD
      name: USD
      target_weight: 0.1
      units: 45000
rebalance:
  abs_threshold_pct: 5
  rel_threshold_pct: 25
tefas:
  default_kind: AUTO
  kind_overrides: {}
